# Generated by Django 4.2.2 on 2023-06-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contato',
            field=models.CharField(max_length=15),
        ),
    ]
