# Generated by Django 4.2.2 on 2023-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0002_alter_paciente_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='consulta',
        ),
    ]
