# Generated by Django 4.2.2 on 2023-06-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0003_remove_paciente_consulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
