# Generated by Django 4.2.2 on 2023-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='espesializacao',
            field=models.CharField(default='especialização', max_length=50),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=14)),
                ('consulta', models.ManyToManyField(to='app_clinica.medico')),
            ],
        ),
    ]
