# Generated by Django 4.2.2 on 2023-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0006_medico_espesializacao_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='Null', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='Nen', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
