# Generated by Django 4.2.2 on 2023-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0007_remove_medico_id_remove_paciente_id_medico_crm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='consulta',
        ),
    ]
