# Generated by Django 4.2.2 on 2023-06-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clinica', '0008_remove_paciente_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consulta',
            field=models.ManyToManyField(to='app_clinica.medico'),
        ),
    ]
